#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>

# bspwm directory
DIR="$HOME/.config/bspwm"

# fix padding
bspc config bottom_padding 0
bspc config top_padding 0

# launch polybar
kill $(ps -aux | grep polybar | cut -d' ' -f8 | tr '\n' ' ') # Kills all instances of polybar
bash "$DIR"/themes/polybar.sh
